version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx_server
    #hostname: geoserver-web
    ports:
      - 8001:80
    volumes:
      - ../../volume/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../volume/nginx:/home
    restart: unless-stopped
    #links:
    #  - database:database

  mysql:
    image: mysql
    container_name: mysql_server
    #hostname: postgis
    ports:
      - 3306:3306
    volumes:
      - ../../volume/mysql:/var/lib/mysql 
      - ../../volume/conf/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: aq1sw2de
      MYSQL_DATABASE: XsGov
      MYSQL_USER: warmgoal
      MYSQL_PASSWORD: aq1sw2de
    restart: unless-stopped