-- DROP USER 'warmgoal'@'%';
-- CREATE USER 'warmgoal'@'%' IDENTIFIED BY 'aq1sw2de';
-- GRANT ALL PRIVILEGES ON *.* TO 'warmgoal'@'%' WITH GRANT OPTION;
-- FLUSH PRIVILEGES;

CHANGE MASTER TO MASTER_HOST='172.16.238.3', MASTER_USER='warmgoal', MASTER_PASSWORD='aq1sw2de', MASTER_RETRY_COUNT=10;
START SLAVE;